In [1]:
# Description: Script to build Table 1
# Dependencies: None
# Authors: Ziming (Alex) Wei
# Last updated: 2024-12-16

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind
from scipy.stats import chi2_contingency

In [37]:
## Table 1
full_data = pd.read_csv('/data/tide/projects/ho_infxn_ml/clean_data/20241210/age_filtered_final_dataset_for_models_20241210.csv')
full_data = full_data[full_data['match'] == 'environmental']

significance_df = []

full_data


match          run    group  group_index  group_binary  \
0      environmental       C_diff     case            1             1   
1      environmental       C_diff  control            1             0   
2      environmental       C_diff     case            2             1   
3      environmental       C_diff  control            2             0   
4      environmental       C_diff     case            3             1   
...              ...          ...      ...          ...           ...   
22016  environmental  VSE_faecium  control          114             0   
22017  environmental  VSE_faecium     case          115             1   
22018  environmental  VSE_faecium  control          115             0   
22019  environmental  VSE_faecium     case          116             1   
22020  environmental  VSE_faecium  control          116             0   

       PatientID          DTS_in_month           DTS_in_year  duration  \
0      Z12531108  2018-07-01T00:00:00Z  2018-01-01T00:00:00Z      22.0   
1      Z17791941  2023-11-01T00:00:00Z  2023-01-01T00:00:00Z       7.1   
2      Z12531108  2018-07-01T00:00:00Z  2018-01-01T00:00:00Z      22.0   
3      Z11757016  2018-04-01T00:00:00Z  2018-01-01T00:00:00Z       7.9   
4      Z12546752  2021-11-01T00:00:00Z  2021-01-01T00:00:00Z      20.8   
...          ...                   ...                   ...       ...   
22016   Z9132834  2021-04-01T00:00:00Z  2021-01-01T00:00:00Z      12.0   
22017  Z10255299  2023-04-01T00:00:00Z  2023-01-01T00:00:00Z      24.9   
22018   Z9689380  2023-06-01T00:00:00Z  2023-01-01T00:00:00Z       8.5   
22019  Z12443485  2017-01-01T00:00:00Z  2017-01-01T00:00:00Z       3.0   
22020  Z13202829  2022-02-01T00:00:00Z  2022-01-01T00:00:00Z       6.0   

       time_to_infxn  ...  prior_VSE_faecium  CDiff_cp   MSSA_cp   MRSA_cp  \
0                4.1  ...                0.0  0.000000  2.348368  0.000000   
1                4.4  ...                0.0  2.463461  6.306123  3.813857   
2               11.7  ...                0.0  0.000000  2.348368  0.000000   
3               11.0  ...                0.0  0.000000  3.647252  0.786879   
4                3.1  ...                0.0  3.763896  2.489342  1.346992   
...              ...  ...                ...       ...       ...       ...   
22016            6.8  ...                0.0  1.944636  5.638387  1.561571   
22017            4.5  ...                0.0  4.729330  3.543732  0.731565   
22018            4.2  ...                0.0  0.938083  0.000000  1.619377   
22019           29.1  ...                0.0  0.000000  0.000000  0.000000   
22020           28.5  ...                0.0  2.347311  3.410294  0.000000   

      DS_Entero_cp   ESBL_cp     VSE_cp    VRE_cp  DS_PsA_cp  DR_PsA_cp  
0         5.042581  1.536687   1.817524  0.000000   0.000000   0.000000  
1        20.965020  8.338228   3.824931  1.416987   1.933492   0.000000  
2         5.042581  1.536687   1.817524  0.000000   0.000000   0.000000  
3        37.925207  9.404443  13.575307  1.622768   1.464393   0.000000  
4        14.896745  7.096428   5.158935  5.013572   3.218728   1.503882  
...            ...       ...        ...       ...        ...        ...  
22016    17.557411  5.057598   4.516640  0.762611   3.745421   1.459764  
22017    13.251243  4.207328   6.554929  3.419085   2.799069   0.768363  
22018     4.616770  0.864746   1.694392  0.744852   1.601416   0.000000  
22019     2.384680  1.507449   1.541314  0.000000   0.000000   0.000000  
22020    11.233866  4.106938   5.638743  0.859328   2.617864   0.978390  

[22021 rows x 74 columns]

In [27]:
## Sample Size

pd.read_csv('/data/tide/projects/ho_infxn_ml/clean_data/20241210/sample_sizes_20241210.csv')

match              run    group  sample_size
0   environmental           C_diff     case          827
1   environmental           C_diff  control         1311
2   environmental  DR_P_aeruginosa     case          247
3   environmental  DR_P_aeruginosa  control          321
4   environmental     DS_E_cloacae     case          279
..            ...              ...      ...          ...
67        patient      VRE_faecium  control           21
68        patient     VSE_faecalis     case          124
69        patient     VSE_faecalis  control          127
70        patient      VSE_faecium     case           18
71        patient      VSE_faecium  control           19

[72 rows x 4 columns]

In [21]:
full_data[full_data['run'] == 'C_diff']

match     run    group  group_index  group_binary  PatientID  \
0     environmental  C_diff     case            1             1  Z12531108   
1     environmental  C_diff  control            1             0  Z17791941   
2     environmental  C_diff     case            2             1  Z12531108   
3     environmental  C_diff  control            2             0  Z11757016   
4     environmental  C_diff     case            3             1  Z12546752   
...             ...     ...      ...          ...           ...        ...   
2171  environmental  C_diff  control          825             0  Z15820380   
2172  environmental  C_diff     case          826             1  Z10260632   
2173  environmental  C_diff  control          826             0  Z15820380   
2174  environmental  C_diff     case          827             1  Z10260632   
2175  environmental  C_diff  control          827             0  Z17180269   

              DTS_in_month           DTS_in_year  duration  time_to_infxn  \
0     2018-07-01T00:00:00Z  2018-01-01T00:00:00Z      22.0            4.1   
1     2023-11-01T00:00:00Z  2023-01-01T00:00:00Z       7.1            4.4   
2     2018-07-01T00:00:00Z  2018-01-01T00:00:00Z      22.0           11.7   
3     2018-04-01T00:00:00Z  2018-01-01T00:00:00Z       7.9           11.0   
4     2021-11-01T00:00:00Z  2021-01-01T00:00:00Z      20.8            3.1   
...                    ...                   ...       ...            ...   
2171  2017-07-01T00:00:00Z  2017-01-01T00:00:00Z      17.4            7.3   
2172  2019-08-01T00:00:00Z  2019-01-01T00:00:00Z      11.8            8.0   
2173  2017-07-01T00:00:00Z  2017-01-01T00:00:00Z      17.4            7.3   
2174  2019-08-01T00:00:00Z  2019-01-01T00:00:00Z      11.8            9.1   
2175  2020-02-01T00:00:00Z  2020-01-01T00:00:00Z       3.0            8.8   

      ...  prior_VSE_faecium  CDiff_cp   MSSA_cp   MRSA_cp DS_Entero_cp  \
0     ...                0.0  0.000000  2.348368  0.000000     5.042581   
1     ...                0.0  2.463461  6.306123  3.813857    20.965020   
2     ...                0.0  0.000000  2.348368  0.000000     5.042581   
3     ...                0.0  0.000000  3.647252  0.786879    37.925207   
4     ...                0.0  3.763896  2.489342  1.346992    14.896745   
...   ...                ...       ...       ...       ...          ...   
2171  ...                0.0  0.768448  5.327433  2.652910    20.918696   
2172  ...                0.0  0.000000  6.739872  1.523889    27.181087   
2173  ...                0.0  0.768448  5.327433  2.652910    20.918696   
2174  ...                0.0  0.000000  6.739872  1.523889    27.181087   
2175  ...                0.0  1.647104  6.624713  2.037357    18.048272   

        ESBL_cp     VSE_cp    VRE_cp  DS_PsA_cp  DR_PsA_cp  
0      1.536687   1.817524  0.000000   0.000000   0.000000  
1      8.338228   3.824931  1.416987   1.933492   0.000000  
2      1.536687   1.817524  0.000000   0.000000   0.000000  
3      9.404443  13.575307  1.622768   1.464393   0.000000  
4      7.096428   5.158935  5.013572   3.218728   1.503882  
...         ...        ...       ...        ...        ...  
2171   6.633057   0.443267  0.552517   2.616213   0.000000  
2172  12.917826  10.277529  5.035852   2.203279   2.493618  
2173   6.633057   0.443267  0.552517   2.616213   0.000000  
2174  12.917826  10.277529  5.035852   2.203279   2.493618  
2175   6.900234   6.438336  1.777796   6.276229   2.392997  

[2176 rows x 74 columns]

In [35]:

matched_column = ["age", "sex", "penicillin_0_60", "extended_spectrum_penicillin_0_60", "cephalosporin_0_60", 
                  "extended_spectrum_cephalosporin_0_60", "carbapenem_0_60", "anti_staph_beta_lactam_0_60", 
                  "fluoroquinolone_0_60", "glycopeptide_0_60", "anti_anaerobe_0_60", "anti_Cdiff_0_60",
                  "tetracycline_0_60", "macrolide_0_60", "sulfonamide_0_60", "lincosamide_0_60", "indiv_score", "any_surgery"]

# Age
age_df = full_data[['run', 'group', 'age']]

mean_df = age_df.groupby(by = ['run', 'group'], as_index = False).mean()

sample_size_df = age_df.groupby(by = ['run', 'group'], as_index = False).count()
sample_size_df['age'] = np.sqrt(sample_size_df['age'])

std_df = age_df.groupby(by = ['run', 'group'], as_index = False).std()
std_df.columns = ['run','group','age_se']
std_df['age_se'] = std_df['age_se'] / sample_size_df['age']

age_summary = mean_df.merge(std_df,
                            on = ['run','group'])

age_summary

age_summary['age'] = age_summary['age'].round(2).astype(str) + '+/-' + age_summary['age_se'].round(2).astype(str) 

age_summary = age_summary[['run','group','age']]

for run in age_df['run'].unique():
    
    sub_df = age_df[age_df['run'] == run]
        
    control_sub_df = sub_df[sub_df['group'] == 'control']
    case_sub_df = sub_df[sub_df['group'] == 'case']
    
    t_stat, p_value = ttest_ind(case_sub_df['age'], control_sub_df['age'])
    
    if p_value < 0.05:
        significance = '*'
    else:
        significance = ''
    
    significance_df.append({'variable':'age',
                            'run':run,
                            'significance':significance})


In [36]:
age_summary

run    group           age
0              C_diff     case  66.67+/-0.47
1              C_diff  control  67.41+/-0.34
2     DR_P_aeruginosa     case  69.92+/-0.78
3     DR_P_aeruginosa  control  69.89+/-0.69
4        DS_E_cloacae     case  66.28+/-0.81
5        DS_E_cloacae  control  66.33+/-0.72
6           DS_E_coli     case  68.46+/-0.33
7           DS_E_coli  control  68.77+/-0.29
8        DS_K_oxytoca     case  68.95+/-0.91
9        DS_K_oxytoca  control  69.26+/-0.78
10    DS_K_pneumoniae     case  69.68+/-0.46
11    DS_K_pneumoniae  control  70.19+/-0.41
12    DS_P_aeruginosa     case  70.18+/-0.47
13    DS_P_aeruginosa  control  70.54+/-0.39
14     DS_P_mirabilis     case  70.95+/-0.67
15     DS_P_mirabilis  control  71.79+/-0.54
16    DS_S_marcescens     case   68.9+/-1.08
17    DS_S_marcescens  control  68.74+/-1.02
18     ESBL_E_cloacae     case  67.44+/-0.99
19     ESBL_E_cloacae  control  68.23+/-0.88
20        ESBL_E_coli     case  69.34+/-0.74
21        ESBL_E_coli  control  69.87+/-0.66
22  ESBL_K_pneumoniae     case  68.63+/-0.92
23  ESBL_K_pneumoniae  control  69.15+/-0.78
24   ESBL_P_mirabilis     case  70.83+/-1.12
25   ESBL_P_mirabilis  control  71.61+/-0.95
26               MRSA     case  62.93+/-0.65
27               MRSA  control  63.02+/-0.57
28               MSSA     case  59.53+/-0.47
29               MSSA  control  59.76+/-0.41
30        VRE_faecium     case  65.15+/-0.96
31        VRE_faecium  control  66.12+/-0.84
32       VSE_faecalis     case   69.05+/-0.4
33       VSE_faecalis  control  69.54+/-0.34
34        VSE_faecium     case   68.76+/-1.1
35        VSE_faecium  control  69.47+/-0.97

In [115]:
# Gender
sex_df = full_data[['run', 'group', 'sex']].copy()
sex_df['sex'] = np.where(sex_df['sex'] == 'Male', 1, 0)
sex_summary = sex_df.groupby(['run','group'], as_index=False).mean()
sex_summary

for run in sex_df['run'].unique():
    
    sub_df = sex_df[sex_df['run'] == run]
        
    control_sub_df = sub_df[sub_df['group'] == 'control'].dropna()
    case_sub_df = sub_df[sub_df['group'] == 'case'].dropna()
    
    # Filter for control and case groups, drop NaN values
    control_sub_df = sub_df[sub_df['group'] == 'control'].reset_index(drop=True)
    case_sub_df = sub_df[sub_df['group'] == 'case'].reset_index(drop=True)
    
    # Create a contingency table of sex counts between case and control
    contingency_table = pd.crosstab(sub_df['group'], sub_df['sex'])
    # print(f"Contingency table for run {run}:")
    # print(contingency_table)
    
    chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
    
    if p_value < 0.05:
        significance = '*'
    else:
        significance = ''
    
    significance_df.append({'variable':'sex',
                            'run':run,
                            'significance':significance})
    
# significance_df

In [44]:
# Elixharser Index
elix_df = full_data[['run', 'group', 'indiv_score']]
median_df = elix_df.groupby(by = ['run', 'group'], as_index = False).median()
first_quantile = elix_df.groupby(by = ['run', 'group'], as_index = False).apply(lambda x: x.quantile(0.25))
first_quantile.columns = ['run','group','indiv_score_first_quantile']
third_quantile = elix_df.groupby(by = ['run', 'group'], as_index = False).apply(lambda x: x.quantile(0.75))
third_quantile.columns = ['run','group','indiv_score_third_quantile']
mean_df = elix_df.groupby(by = ['run', 'group'], as_index = False).mean()
mean_df.columns = ['run','group','mean']

std_df = elix_df.groupby(by = ['run', 'group'], as_index = False).std()
std_df.columns = ['run','group','elix_se']
std_df['elix_se'] = std_df['elix_se'] / sample_size_df['age']

elix_summary = median_df.merge(first_quantile,
                              on = ['run','group'])
elix_summary = elix_summary.merge(third_quantile,
                              on = ['run','group'])
elix_summary = elix_summary.merge(mean_df,
                              on = ['run','group'])
elix_summary = elix_summary.merge(std_df,
                              on = ['run','group'])

elix_summary = elix_summary[['run','group','mean','elix_se']]
elix_summary = elix_summary.rename(columns = {'mean':'mean_elix',
                                              'elix_se':'se_elix'})

elix_summary['elix'] = elix_summary['mean_elix'].round(2).astype(str) + ' +/- ' + elix_summary['se_elix'].round(2).astype(str)
elix_summary = elix_summary[['run','group','elix']]
elix_summary

for run in age_df['run'].unique():
    
    sub_df = elix_df[elix_df['run'] == run]
        
    control_sub_df = sub_df[sub_df['group'] == 'control']
    case_sub_df = sub_df[sub_df['group'] == 'case']
    
    t_stat, p_value = ttest_ind(case_sub_df['indiv_score'], control_sub_df['indiv_score'])
    
    if p_value < 0.05:
        significance = '*'
    else:
        significance = ''
    
    significance_df.append({'variable':'indiv_score',
                            'run':run,
                            'significance':significance})


In [45]:
elix_summarymmary

run    group           elix
0              C_diff     case  1.02 +/- 0.13
1              C_diff  control  0.74 +/- 0.09
2     DR_P_aeruginosa     case  1.02 +/- 0.25
3     DR_P_aeruginosa  control  0.95 +/- 0.21
4        DS_E_cloacae     case  0.56 +/- 0.16
5        DS_E_cloacae  control  0.52 +/- 0.14
6           DS_E_coli     case  0.36 +/- 0.06
7           DS_E_coli  control  0.32 +/- 0.05
8        DS_K_oxytoca     case  0.56 +/- 0.19
9        DS_K_oxytoca  control  0.43 +/- 0.15
10    DS_K_pneumoniae     case  0.65 +/- 0.11
11    DS_K_pneumoniae  control  0.55 +/- 0.09
12    DS_P_aeruginosa     case   0.63 +/- 0.1
13    DS_P_aeruginosa  control  0.52 +/- 0.08
14     DS_P_mirabilis     case  0.45 +/- 0.14
15     DS_P_mirabilis  control   0.34 +/- 0.1
16    DS_S_marcescens     case  0.57 +/- 0.25
17    DS_S_marcescens  control  0.48 +/- 0.24
18     ESBL_E_cloacae     case   1.9 +/- 0.36
19     ESBL_E_cloacae  control   1.7 +/- 0.31
20        ESBL_E_coli     case   0.8 +/- 0.18
21        ESBL_E_coli  control  0.73 +/- 0.17
22  ESBL_K_pneumoniae     case  1.28 +/- 0.28
23  ESBL_K_pneumoniae  control  1.15 +/- 0.24
24   ESBL_P_mirabilis     case  0.19 +/- 0.18
25   ESBL_P_mirabilis  control  0.14 +/- 0.13
26               MRSA     case  0.72 +/- 0.14
27               MRSA  control  0.62 +/- 0.11
28               MSSA     case  0.57 +/- 0.08
29               MSSA  control  0.44 +/- 0.06
30        VRE_faecium     case  1.07 +/- 0.28
31        VRE_faecium  control  0.85 +/- 0.23
32       VSE_faecalis     case   0.6 +/- 0.09
33       VSE_faecalis  control   0.5 +/- 0.07
34        VSE_faecium     case  1.05 +/- 0.35
35        VSE_faecium  control   0.88 +/- 0.3

In [117]:
# Surgery
surgery_df = full_data[['run', 'group', 'any_surgery']].copy()
surgery_summary = surgery_df.groupby(['run','group'], as_index=False).mean()
surgery_summary

for run in surgery_df['run'].unique():
    
    sub_df = surgery_df[surgery_df['run'] == run]
        
    control_sub_df = sub_df[sub_df['group'] == 'control'].dropna()
    case_sub_df = sub_df[sub_df['group'] == 'case'].dropna()
    
    # Filter for control and case groups, drop NaN values
    control_sub_df = sub_df[sub_df['group'] == 'control'].reset_index(drop=True)
    case_sub_df = sub_df[sub_df['group'] == 'case'].reset_index(drop=True)
    
    # Create a contingency table of surgery counts between case and control
    contingency_table = pd.crosstab(sub_df['group'], sub_df['any_surgery'])
    
    chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
    
    if p_value < 0.05:
        significance = '*'
    else:
        significance = ''
    
    significance_df.append({'variable':'any_surgery',
                            'run':run,
                            'significance':significance})
    

In [118]:
# Prior Abx
abx_df = full_data.filter(regex='_0_60$').copy()
abx_df['run'] = full_data['run']
abx_df['group'] = full_data['group']

abs_summary = abx_df.groupby(['run','group'], as_index=False).mean()
abs_summary

for variable in abx_df.columns.drop(['run','group']):
    
    one_abx_df = abx_df[['run','group',variable]]
    
    for run in one_abx_df['run'].unique():

        sub_df = one_abx_df[one_abx_df['run'] == run]

        control_sub_df = sub_df[sub_df['group'] == 'control'].dropna()
        case_sub_df = sub_df[sub_df['group'] == 'case'].dropna()

        # Filter for control and case groups, drop NaN values
        control_sub_df = sub_df[sub_df['group'] == 'control'].reset_index(drop=True)
        case_sub_df = sub_df[sub_df['group'] == 'case'].reset_index(drop=True)

        # Create a contingency table of sex counts between case and control
        contingency_table = pd.crosstab(sub_df['group'], sub_df[variable])

        chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

        if p_value < 0.05:
            significance = '*'
        else:
            significance = ''

        significance_df.append({'variable':variable,
                                'run':run,
                                'significance':significance})
    

In [119]:
for column in abx_df.columns:
    print(column)
    print(abx_df[column].unique())

any_abx_0_60
[0 1]
anti_anaerobe_0_60
[0 1]
anti_Cdiff_0_60
[0]
anti_staph_beta_lactam_0_60
[0]
carbapenem_0_60
[0]
cephalosporin_0_60
[0 2 1 3 4 6]
extended_spectrum_cephalosporin_0_60
[0 2]
extended_spectrum_penicillin_0_60
[0 2 1 3 4]
fluoroquinolone_0_60
[0 2 3 6 1]
glycopeptide_0_60
[0]
lincosamide_0_60
[0 2 1]
macrolide_0_60
[0 2 1 3]
penicillin_0_60
[0 1 2 5]
sulfonamide_0_60
[0 1 3 2]
tetracycline_0_60
[0 2 1]
run
['C_diff' 'DR_P_aeruginosa' 'DS_E_cloacae' 'DS_E_coli' 'DS_K_oxytoca'
 'DS_K_pneumoniae' 'DS_P_aeruginosa' 'DS_P_mirabilis' 'DS_S_marcescens'
 'ESBL_E_cloacae' 'ESBL_E_coli' 'ESBL_K_pneumoniae' 'ESBL_P_mirabilis'
 'MRSA' 'MSSA' 'VRE_faecium' 'VSE_faecalis' 'VSE_faecium']
group
['case' 'control']


In [120]:
# Prior Infection
selected_organism = ['C_diff', 'DR_P_aeruginosa', 'DS_E_coli', 'DS_K_pneumoniae',
                     'DS_P_aeruginosa', 'ESBL_E_coli', 'ESBL_K_pneumoniae',
                     'MRSA', 'MSSA', 'VRE_faecium', 'VSE_faecalis']
prior_infection_list = ['prior_' + organism for organism in selected_organism]

full_data = full_data[full_data['run'].isin(selected_organism)]
full_data = full_data[['run','group'] + prior_infection_list]

mean_df = full_data.groupby(by=['run','group'],as_index=False).mean()
first_quantile_df = full_data.groupby(by=['run','group'],as_index=False).quantile(0.25)
third_quantile_df = full_data.groupby(by=['run','group'],as_index=False).quantile(0.75)

In [13]:
full_data = pd.read_csv('/data/tide/projects/ho_infxn_ml/clean_data/20241207/both_matched_final_dataset_for_models_20241207.csv')
full_data = full_data[full_data['match'] == 'environmental']
micro = pd.read_csv("/data/tide/projects/ho_infxn_ml/clean_data/20241105/micro_dedup.csv")
micro = micro[micro['PatientID'].isin(full_data['PatientID'])]
micro = micro[micro['org_group_3'].isin(selected_organism)]
micro = micro[['PatientID','coll_datetime_UTC','org_group_3']]
micro = micro.rename(columns = {'coll_datetime_UTC': 'prior_infection_time',
                                'org_group_3': 'prior_infection'})
micro = micro.merge(full_data[['match','run','group','PatientID','DTS_in_month','duration']],
                    on = 'PatientID',
                    how = 'left')
micro['time_difference'] = pd.to_datetime(micro['prior_infection_time']) - pd.to_datetime(micro['DTS_in_month']) 
micro['time_difference'] = micro['time_difference'].dt.days

micro = micro[(micro['time_difference'] <= -27) & (micro['time_difference'] >= -150)]
micro = micro[['PatientID','prior_infection','match','run','group']]
micro = micro.drop_duplicates()
micro = pd.get_dummies(micro,
                       columns = ['prior_infection'])
micro = micro.groupby(['PatientID','group','match','run'],as_index=False).sum()
micro

FileNotFoundError: [Errno 2] No such file or directory: '/data/tide/projects/ho_infxn_ml/clean_data/20241207/both_matched_final_dataset_for_models_20241207.csv'

In [122]:
prior_infection_df = full_data.merge(micro,
                                     on = ['PatientID','match','run','group'],
                                     how = 'left')
prior_infection_df = prior_infection_df.fillna(0)
prior_infection_df

match          run    group  group_index  group_binary  \
0      environmental       C_diff     case            1             1   
1      environmental       C_diff  control            1             0   
2      environmental       C_diff  control            1             0   
3      environmental       C_diff  control            1             0   
4      environmental       C_diff     case            2             1   
...              ...          ...      ...          ...           ...   
24678  environmental  VSE_faecium  control          162             0   
24679  environmental  VSE_faecium     case          163             1   
24680  environmental  VSE_faecium  control          163             0   
24681  environmental  VSE_faecium     case          164             1   
24682  environmental  VSE_faecium  control          164             0   

       PatientID          DTS_in_month           DTS_in_year  duration  \
0       Z9548945  2018-02-01T00:00:00Z  2018-01-01T00:00:00Z       3.9   
1       Z6649912  2024-03-01T00:00:00Z  2024-01-01T00:00:00Z       3.9   
2       Z6649912  2024-03-01T00:00:00Z  2024-01-01T00:00:00Z       3.9   
3       Z6649912  2024-03-01T00:00:00Z  2024-01-01T00:00:00Z       3.9   
4       Z9548945  2018-02-01T00:00:00Z  2018-01-01T00:00:00Z       3.9   
...          ...                   ...                   ...       ...   
24678   Z7814122  2016-05-01T00:00:00Z  2016-01-01T00:00:00Z       4.0   
24679   Z8974083  2017-05-01T00:00:00Z  2017-01-01T00:00:00Z       2.7   
24680   Z9460315  2022-11-01T00:00:00Z  2022-01-01T00:00:00Z       2.8   
24681   Z9115053  2020-03-01T00:00:00Z  2020-01-01T00:00:00Z      15.8   
24682  Z17573926  2019-10-01T00:00:00Z  2019-01-01T00:00:00Z       5.0   

       time_to_infxn  ...  prior_infection_DR_P_aeruginosa  \
0              -36.1  ...                              0.0   
1             -262.1  ...                              0.0   
2             -155.0  ...                              0.0   
3              -92.9  ...                              0.0   
4               -0.2  ...                              0.0   
...              ...  ...                              ...   
24678           28.0  ...                              0.0   
24679            3.2  ...                              0.0   
24680         -287.3  ...                              0.0   
24681            0.1  ...                              0.0   
24682            0.1  ...                              0.0   

      prior_infection_DS_E_coli  prior_infection_DS_K_pneumoniae  \
0                           0.0                              1.0   
1                           0.0                              1.0   
2                           0.0                              1.0   
3                           0.0                              1.0   
4                           0.0                              1.0   
...                         ...                              ...   
24678                       0.0                              0.0   
24679                       0.0                              0.0   
24680                       0.0                              0.0   
24681                       0.0                              0.0   
24682                       0.0                              0.0   

       prior_infection_DS_P_aeruginosa prior_infection_ESBL_E_coli  \
0                                  0.0                         0.0   
1                                  0.0                         0.0   
2                                  0.0                         0.0   
3                                  0.0                         0.0   
4                                  0.0                         0.0   
...                                ...                         ...   
24678                              0.0                         0.0   
24679                              0.0                         0.0   
24680                              0.0                   

In [123]:
for variable in prior_infection_list:
    
    one_pi_df = prior_infection_df[['run','group',variable]]

    for run in one_pi_df['run'].unique():

        sub_df = one_pi_df[one_pi_df['run'] == run]

        control_sub_df = sub_df[sub_df['group'] == 'control']
        case_sub_df = sub_df[sub_df['group'] == 'case']

        t_stat, p_value = ttest_ind(case_sub_df[variable], control_sub_df[variable])

        if p_value < 0.05:
            significance = '*'
        else:
            significance = ''

        significance_df.append({'variable':variable,
                                'run':run,
                                'significance':significance})


In [124]:
prior_infection_df = prior_infection_df.loc[:,prior_infection_df.columns.isin(['run','group']) | prior_infection_df.columns.str.startswith('prior_infection')]
prior_infection_df = prior_infection_df.groupby(['run','group'], as_index=False).mean()
prior_infection_df = prior_infection_df[prior_infection_df['run'].isin(selected_organism)]
prior_infection_df

run    group  prior_infection_C_diff  \
0              C_diff     case                0.000000   
1              C_diff  control                0.000000   
2     DR_P_aeruginosa     case                0.010204   
3     DR_P_aeruginosa  control                0.005063   
6           DS_E_coli     case                0.000478   
7           DS_E_coli  control                0.016981   
10    DS_K_pneumoniae     case                0.003922   
11    DS_K_pneumoniae  control                0.015337   
12    DS_P_aeruginosa     case                0.004454   
13    DS_P_aeruginosa  control                0.012678   
20        ESBL_E_coli     case                0.011881   
21        ESBL_E_coli  control                0.006079   
22  ESBL_K_pneumoniae     case                0.000000   
23  ESBL_K_pneumoniae  control                0.007519   
26               MRSA     case                0.005725   
27               MRSA  control                0.009915   
28               MSSA     case                0.000000   
29               MSSA  control                0.011307   
30        VRE_faecium     case                0.021459   
31        VRE_faecium  control                0.009615   
32       VSE_faecalis     case                0.005008   
33       VSE_faecalis  control                0.010645   

    prior_infection_DR_P_aeruginosa  prior_infection_DS_E_coli  \
0                          0.016393                   0.052823   
1                          0.001362                   0.092643   
2                          0.000000                   0.027211   
3                          0.000000                   0.070886   
6                          0.004785                   0.000000   
7                          0.019245                   0.000000   
10                         0.016993                   0.052288   
11                         0.008180                   0.094070   
12                         0.013363                   0.028953   
13                         0.007924                   0.091125   
20                         0.000000                   0.069307   
21                         0.012158                   0.104863   
22                         0.009524                   0.071429   
23                         0.003759                   0.048872   
26                         0.003817                   0.040076   
27                         0.008499                   0.059490   
28                         0.004419                   0.017677   
29                         0.015830                   0.077341   
30                         0.030043                   0.042918   
31                         0.003205                   0.070513   
32                         0.005008                   0.053422   
33                         0.011897                   0.083907   

    prior_infection_DS_K_pneumoniae  prior_infection_DS_P_aeruginosa  \
0                          0.025501                         0.020036   
1                          0.046322                         0.017711   
2                          0.037415                         0.105442   
3                          0.043038                         0.025316   
6                          0.009569                         0.010048   
7                          0.038491                         0.032830   
10                         0.000000                         0.016993   
11                         0.000000                         0.024540   
12                         0.031180                         0.000000   
13                         0.044374                         0.000000   
20                         0.025743                         0.007921   
21                         0.031915                         0.022796   
22                         0.038095                         0.052381   
23                         0.018797                         0.003759   
26                         0.009542                         0.024809   
27          

In [125]:
# Merge All Dataframes
table1 = age_summary.merge(sex_summary,
                          on = ['run','group'])
table1 = table1.merge(elix_summary,
                      on = ['run','group'])
table1 = table1.merge(surgery_summary,
                      on = ['run','group'])
table1 = table1.merge(abs_summary,
                      on = ['run','group'])
table1 = table1.merge(prior_infection_df,
                      on = ['run','group'])

table1_melted = pd.melt(
    table1, 
    id_vars=["run", "group"], 
    value_vars=table1.columns.drop(['run','group']),
    var_name="variable", 
    value_name="value"
)

table1_pivoted = table1_melted.pivot(
    index=["run", "variable"], 
    columns="group", 
    values="value"
).reset_index()

significance_df = pd.DataFrame(significance_df)

table1_pivoted['variable'] = table1_pivoted['variable'].str.replace('infection_', '', regex=False)
significance_df['variable'] = significance_df['variable'].str.replace('indiv_score', 'elix', regex=False)

table1_pivoted = table1_pivoted.merge(significance_df,
                                      on = ['run','variable'],
                                      how = 'left')

table1_pivoted

run                     variable           case        control  \
0          C_diff                          age  66.67+/-13.41  67.41+/-12.63   
1          C_diff              anti_Cdiff_0_60              0              0   
2          C_diff           anti_anaerobe_0_60     0.00120919     0.00074129   
3          C_diff  anti_staph_beta_lactam_0_60              0              0   
4          C_diff                 any_abx_0_60      0.0423216      0.0355819   
..            ...                          ...            ...            ...   
325  VSE_faecalis            prior_VRE_faecium     0.00417362     0.00688791   
326  VSE_faecalis           prior_VSE_faecalis              0              0   
327  VSE_faecalis                          sex       0.471785       0.473142   
328  VSE_faecalis             sulfonamide_0_60     0.00832562     0.00662252   
329  VSE_faecalis            tetracycline_0_60     0.00462535     0.00515085   

    significance  
0                 
1                 
2                 
3                 
4                 
..           ...  
325               
326               
327               
328               
329               

[330 rows x 5 columns]

In [126]:
table1_pivoted[table1_pivoted['significance'].isna()]

Empty DataFrame
Columns: [run, variable, case, control, significance]
Index: []

In [127]:
table1_pivoted.to_csv('/data/tide/projects/ho_infxn_ml/clean_data/20241210/Table1_Baseline_cohort_characteristics.csv',
               index = False)
table1_pivoted.to_csv('/PHShome/zw852/hospital_onset_personal_folder/Table1_Baseline_cohort_characteristics.csv',
               index = False)